import './Course.css';
const Course = () => {
    return (
        <div className='Course'>
            <section className="Course_start">
                <h2>코스소개</h2>
                <article className='Course_first'>
                    <div className="Course_img"></div>
                </article>
                <article className="Course_dongak">
                    <aside>
                        <div></div>
                        <h2>동악코스</h2>
                    </aside>
                    <aside>
                        <table>
                            <tr>
                                <td>구분</td>
                                <td>1H</td>
                                <td>2H</td>
                                <td>3H</td>
                                <td>4H</td>
                                <td>5H</td>
                                <td>6H</td>
                                <td>7H</td>
                                <td>8H</td>
                                <td>9H</td>
                                <td>Total</td>
                            </tr>
                            <tr>
                                <td>H.D.C.P</td>
                                <td>9</td>
                                <td>1</td>
                                <td>3</td>
                                <td>5</td>
                                <td>6</td>
                                <td>7</td>
                                <td>8</td>
                                <td>2</td>
                                <td>4</td>
                                <td>-</td>
                            </tr>
                            <tr>
                                <td>C.T(m)</td>
                                <td>365</td>
                                <td>398</td>
                                <td>509</td>
                                <td>360</td>
                                <td>162</td>
                                <td>480</td>
                                <td>336</td>
                                <td>199</td>
                                <td>345</td>
                                <td>3,154</td>
                            </tr>
                            <tr>
                                <td>R.T(m)</td>
                                <td>351</td>
                                <td>384</td>
                                <td>492</td>
                                <td>352</td>
                                <td>150</td>
                                <td>463</td>
                                <td>324</td>
                                <td>186</td>
                                <td>328</td>
                                <td>3,030</td>
                            </tr>
                            <tr>
                                <td>L.T(m)</td>
                                <td>292</td>
                                <td>293</td>
                                <td>414</td>
                                <td>299</td>
                                <td>116</td>
                                <td>417</td>
                                <td>263</td>
                                <td>119</td>
                                <td>252</td>
                                <td>2,465</td>
                            </tr>
                            <tr>
                                <td>PAR</td>
                                <td>4</td>
                                <td>4</td>
                                <td>5</td>
                                <td>4</td>
                                <td>3</td>
                                <td>5</td>
                                <td>4</td>
                                <td>3</td>
                                <td>4</td>
                                <td>36</td>
                            </tr>
                        </table>
                    </aside>
                </article>
                <article className="Course_sumjin">
                    <aside>
                        <div></div>
                        <h2>섬진코스</h2>
                    </aside>
                    <aside>
                        <table>
                            <tr>
                                <td>구분</td>
                                <td>1H</td>
                                <td>2H</td>
                                <td>3H</td>
                                <td>4H</td>
                                <td>5H</td>
                                <td>6H</td>
                                <td>7H</td>
                                <td>8H</td>
                                <td>9H</td>
                                <td>Total</td>
                            </tr>
                            <tr>
                                <td>H.D.C.P</td>
                                <td>4</td>
                                <td>8</td>
                                <td>3</td>
                                <td>7</td>
                                <td>2</td>
                                <td>5</td>
                                <td>9</td>
                                <td>6</td>
                                <td>1</td>
                                <td>-</td>
                            </tr>
                            <tr>
                                <td>C.T(m)</td>
                                <td>371</td>
                                <td>328</td>
                                <td>185</td>
                                <td>543</td>
                                <td>396</td>
                                <td>491</td>
                                <td>314</td>
                                <td>176</td>
                                <td>375</td>
                                <td>3,179</td>
                            </tr>
                            <tr>
                                <td>R.T(m)</td>
                                <td>357</td>
                                <td>309</td>
                                <td>173</td>
                                <td>527</td>
                                <td>379</td>
                                <td>468</td>
                                <td>301</td>
                                <td>167</td>
                                <td>354</td>
                                <td>3,035</td>
                            </tr>
                            <tr>
                                <td>L.T(m)</td>
                                <td>322</td>
                                <td>352</td>
                                <td>148</td>
                                <td>447</td>
                                <td>304</td>
                                <td>407</td>
                                <td>252</td>
                                <td>137</td>
                                <td>271</td>
                                <td>2,540</td>
                            </tr>
                            <tr>
                                <td>PAR</td>
                                <td>4</td>
                                <td>4</td>
                                <td>3</td>
                                <td>5</td>
                                <td>4</td>
                                <td>5</td>
                                <td>4</td>
                                <td>3</td>
                                <td>4</td>
                                <td>36</td>
                            </tr>
                        </table>
                    </aside>
                </article>
                <article className="Course_sulsan">
                    <aside>
                        <div></div>
                        <h2>설산코스</h2>
                    </aside>
                    <aside>
                        <table>
                            <tr>
                                <td>구분</td>
                                <td>1H</td>
                                <td>2H</td>
                                <td>3H</td>
                                <td>4H</td>
                                <td>5H</td>
                                <td>6H</td>
                                <td>7H</td>
                                <td>8H</td>
                                <td>9H</td>
                                <td>Total</td>
                            </tr>
                            <tr>
                                <td>H.D.C.P</td>
                                <td>6</td>
                                <td>2</td>
                                <td>8</td>
                                <td>3</td>
                                <td>1</td>
                                <td>4</td>
                                <td>5</td>
                                <td>9</td>
                                <td>7</td>
                                <td>-</td>
                            </tr>
                            <tr>
                                <td>C.T(m)</td>
                                <td>371</td>
                                <td>395</td>
                                <td>158</td>
                                <td>490</td>
                                <td>393</td>
                                <td>154</td>
                                <td>501</td>
                                <td>330</td>
                                <td>332</td>
                                <td>3,124</td>
                            </tr>
                            <tr>
                                <td>R.T(m)</td>
                                <td>354</td>
                                <td>380</td>
                                <td>134</td>
                                <td>474</td>
                                <td>380</td>
                                <td>142</td>
                                <td>490</td>
                                <td>302</td>
                                <td>312</td>
                                <td>2,968</td>
                            </tr>
                            <tr>
                                <td>L.T(m)</td>
                                <td>309</td>
                                <td>334</td>
                                <td>106</td>
                                <td>417</td>
                                <td>330</td>
                                <td>115</td>
                                <td>383</td>
                                <td>239</td>
                                <td>212</td>
                                <td>2,445</td>
                            </tr>
                            <tr>
                                <td>PAR</td>
                                <td>4</td>
                                <td>4</td>
                                <td>3</td>
                                <td>5</td>
                                <td>4</td>
                                <td>3</td>
                                <td>5</td>
                                <td>4</td>
                                <td>4</td>
                                <td>36</td>
                            </tr>
                        </table>
                    </aside>
                </article>
            </section>
        </div>
    );
}

export default Course;